title: Enric Llonch
description: Un blog personal força impersonal, fet a estones per Enric Llonch. Escric sobre música, cultura popular, tecnologia i qualsevol altra cosa. Quan tinc temps.
url: https://enricllonch.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
author:
  twitter: enricll

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 10

navigation:
 - title: Blog
   url: /index.html
 - title: Colophon
   url: /about

social:
  name: Enric Llonch
  links:
    - twitter: https://twitter.com/enricll
    - linkedin: https://www.linkedin.com/in/enricllonch/

plugins:
 - jekyll-sitemap
