title: Enric Llonch
description: Un blog personal força impersonal.

url: http://enricll.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: 
   twitter: 
   facebook: 
   email:
